config/routes.rb
Rails.application.routes.draw do
    
  scope module: 'public' do
    
    resources :pictures
    resources :albums do
      resource :pictures
    end

    root 'albums#index'

    delete "log_out", to: "sessions#destroy", as: "destroy_user_session"
    get "log_in", to: "sessions#new", as: "new_user_session"
    post "confirm_account_create", to: "confirmations#create", as: "confirmations"
    get "confirm_account_edit", to: "confirmations#edit", as: "confirmations_edit"
    post "confirm_account_update", to: "confirmations#update", as: "confirmations_update"


    get 'password_new', to: "passwords#new", as: 'password_new'
    post 'password_create', to: "passwords#create", as: 'password_create'
    get 'password_edit', to: "passwords#edit", as: 'password_edit'
    post 'password_update', to: 'passwords#update', as: 'password_update'

    resources :users
    resources :sessions
    resources :confirmations
    resources :passwords
  end
  

  namespace :admin do
    
    resources :pictures
    resources :albums do
      resource :pictures
    end

    root 'albums#index'

    delete "log_out", to: "sessions#destroy", as: "destroy_user_session"
    get "pictures/:id/make_protected", to: "pictures#make_protected", as: "pictures_make_protected"
    get "sign_up", to: "users#new", as: "new_user_registration"
    


    resources :users
    resources :sessions
    #resources :confirmations

  end
  
end

app/models/album.rb
class Album < ActiveRecord::Base

	has_many :pictures, dependent: :destroy
	accepts_nested_attributes_for :pictures, allow_destroy: true
	validates_presence_of :name

  def self.find_updated_and_new(albums)
    album_array = [].to_set
    albums.each do |a|
      if a.pictures.length > 0 
        a.pictures.each do |p|
          if p.created_at.to_date == Date.yesterday and !p.protected
            album_array << a 
          end
        end
      end
    end
    album_array
  end

  def self.email_update
    albums = find_updated_and_new(Album.all)
    if albums.length > 0
      User.all.each do |u|
        PhotoAppMailer.email_updates_albums(u, albums).deliver
      end
    end
  end

end

app/controllers/admin/albums_controller.rb
class Admin::AlbumsController < ApplicationController

  before_filter :authenticate_admin

  layout 'admin'

  def index
    @albums = Album.all.order(:id).paginate(page: params[:page], per_page: 10)
  end

  def new
    @album = Album.new
  end

  def create
    @album = Album.create(album_params)

    @result = @album.save
    respond_to do |f|
      f.js
      f.html {
        redirect_to action: :index
        flash[:notice] = 'Album succesfully created'
      }
    end
    
  end

  def edit
    @album = Album.find(params[:id])
    @picture = Picture.new
    @pictures = @album.pictures.paginate(page: params[:page], per_page: 20)
  end

  def update
    @album = Album.find(params[:id])
    @result = @album.update(album_params)
    if @result
      if params[:picture]
        params[:picture].each do |k,v|
          @save = @album.pictures.create(upload: v)
          @type = @save.content_type(@save)
        end
      end
    end
    @new_picture = @album.pictures.order('created_at').last
    respond_to do |f|
      f.js
      f.html {
        redirect_to action: :index
        flash[:notice] = 'Album succesfully updated'
      }
    end
  end

  def destroy
    @album = Album.find(params[:id])
    @destroy = @album.destroy
    if @destroy
      redirect_to action: :index
      flash[:notice] = 'The album has been successfully deleted!'
    else
      redirect_to :back, alert: 'There was an error in deleting the album, please try again'
    end
  end

  private

  def album_params
    params.require(:album).permit(:name, :cover, :created_by, pictures_attributes: [:upload, :name, :album_id, :id])
  end

end

app/helpers/albums_helper.rb
module AlbumsHelper

  def media_file_icon(content_type)
    klass = if content_type.match(/zip|rar|tar/)
      'compressed'
    elsif content_type.match(/video|flv-application|x-mp4/)
      'film'
    else
      'file'
    end

    content_tag(:i, nil, class: klass + ' file-icon glyphicon glyphicon-' + klass)
  end
  
  def is_protected(file)
    !file.protected ? klass = 'btn-default' : klass = 'btn-success'
    klass
  end

end

app/views/admin/albums/_form.html.erb
<%= form_for [:admin, @album], html: {multipart: true} do |f| %>

	<div class="row">
    <div class="form-group col-md-4">
      <label>Album cover</label>
      <br class="album-break">
      <div class="album-cover-edit">
        <div class="inner-box droppable">
          <% if !@album.cover.nil? %>
            <% if @album.cover.length > 0 %>
             <%= image_tag(@album.cover, id: 'album-cover', alt: "album cover", class: "img-thumbnail draggable ui-widget-content" ) %>
            <% end %>
          <% end %>
          <div class="delete-cover">
            <span>Remove cover</span>
          </div>
          <p>Drag and drop one of the photos here</p>
        </div>
      </div>      
    </div>  

    <div class="col-md-3 col-sm3">
      <div class="row">
        <div class="col-md-12 col-sm-12 form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: "form-control", autofocus: true %>
        </div>
      </div>
      <div class="row">
        <div class="form-group col-md-12 col-sm-12">
          <%= f.hidden_field :cover, class: "form-control ui-widget-header" %>
          <%= f.submit "Save album", class: "btn btn-success" %>
        </div>  
      </div>
    </div>
  </div>
  <%= f.fields_for :pictures, @album.pictures.build do |upload| %>
		<div class="row">
			<div class="col-md-4">
				<h4>Add files</h4>
				<%= file_field_tag 'picture[upload]', multiple: true, id: 'picture_upload' %>
			</div>
		</div>
	<% end %>
<% end %>

<br class="end-of-form">

<% if @pictures.images.length > 0 %>
<div class="row">
	<div class="col-md-12">
    <h3>Photos</h3>
    <table class="table-custom pic-list">
      <% @pictures.images.each do |picture| %>
        <% if picture.id %>
          <tr>
            <td class="image gallery">
              <%= link_to(image_tag(picture.upload.url(:small),
              id: picture.id, 
              alt: "photo", 
              class: "img draggable ui-widget-content" ),
              picture.upload.url,
              target: '_blank'
              ) 
              %>
            </td>
            <td>
              <%= picture.upload.original_filename %>
            </td>
            <td class="buttons pull-right">
              <%= link_to 'Private',
                admin_pictures_make_protected_path(picture),
                class: "btn #{ is_protected(picture) } protected",
                remote: true, title: 'Private'
              %>
              <%= link_to 'Delete',
                [:admin, picture],
                method: :delete,
                class: 'btn btn-danger delete-file',
                data: { confirm: 'Are you sure you want to delete this picture?', toggle: 'tooltip', placement: 'bottom' },
                remote: true, title: 'Delete photo'
              %>
            </td>
          </tr>
        <% end %>  
      <% end %>
    </table>
    <br>
  <% else %>
    <p class="no-content">There are no images in this album</p>
  <% end %>
  <% if @pictures.files.length > 0 %>
    <h3>Files</h3>
    <table class="table-custom file-list">
      <% @pictures.files.each do |picture| %>
        <% if picture.id %>
          <tr>
            <td class="file">
              <%= link_to media_file_icon(picture.upload_content_type),picture.upload.url, target: '_blank' %>
            </td>
            <td>
              <%= link_to picture.upload.original_filename,picture.upload.url, target: '_blank' %>  
            </td>
            <td class="buttons pull-right">
              <%= link_to 'Private',
                admin_pictures_make_protected_path(picture),
                class: "btn #{ is_protected(picture) } protected",
                remote: true, title: 'Private'
              %>
              <%= link_to 'Delete',
                [:admin, picture],
                method: :delete,
                class: 'btn btn-danger delete-file',
                data: { confirm: 'Are you sure you want to delete this picture?', toggle: 'tooltip', placement: 'bottom' },
                remote: true, title: 'Delete photo'
              %>
            </td>
          </tr>
        <% end %>  
      <% end %>
    </table>
	<% end %>
  <%= will_paginate @pictures %>
  </div>
</div>

app/views/admin/albums/_index.html.erb
<div class="new-album-controlls">
  <%= form_for [:admin, album], html: {method: :post, remote: true } do |f| %>
    <div class="row">
      <div class="col-md-9 col-sm-9 col-xs-9">
        <%= f.text_field :name, class: "form-control", autofocus: true, placeholder: 'Name' %>
      </div>
      <%= f.hidden_field :created_by, value: current_user.name %>
      <div class="">
        <%= f.submit "Add", class: "btn btn-sm btn-success" %>
      </div>
    </div>

  <% end %>
  <div class="plus">
    <p>Add new album<span class="glyphicon glyphicon-plus-sign pull-right"></span></p>
  </div>
</div>
<h4><a href="/admin">Albums</a></h4>

<ul class="album-list">
  <% albums.each do |album| %>
    <li class="<%= active_page(edit_admin_album_path(album)) %>"> 
      
      <div class="action">
        <%= link_to '',
          [:admin, album],
          method: :delete,
          class: 'pull-right glyphicon glyphicon-remove-circle album-delete-icon delete-album',
          data: { confirm: 'Are you sure you want to delete this album?', toggle: "tooltip", placement: "bottom" }, 
          title: "Delete album"
        %>
      </div>
      <%= link_to album.name, edit_admin_album_path(album), class: 'left-link ' %>
    </li>
  <% end %>
</ul>
<br>

app/views/admin/albums/_single_album.html.erb
<li class="<%= active_page(edit_admin_album_path(album)) %>">   
  <div class="action">
    <%= link_to '',
      [:admin, album],
      method: :delete,
      class: 'pull-right glyphicon glyphicon-remove-circle album-delete-icon',
      data: { confirm: 'Are you sure you want to delete this album?', toggle: "tooltip", placement: "bottom" }, 
      title: "Delete album"
    %>
  </div>
  <%= link_to album.name, edit_admin_album_path(album), class: 'left-link ' %>
</li>

app/views/admin/albums/_single_file.html.erb
<tr>
  <td class="file">
    <%= link_to media_file_icon(picture.upload_content_type),picture.upload.url, target: '_blank' %>
  </td>
  <td>
    <%= link_to picture.upload.original_filename,picture.upload.url, target: '_blank' %>  
  </td>
  <td class="buttons pull-right">
    <%= link_to 'Private',
      admin_pictures_make_protected_path(picture),
      class: "btn #{ is_protected(picture) } protected",
      remote: true, title: 'Private'
    %>
    <%= link_to 'Delete',
      [:admin, picture],
      method: :delete,
      class: 'btn btn-danger delete-file', 
      data: { confirm: 'Are you sure you want to delete this picture?', toggle: 'tooltip', placement: 'bottom' },
      remote: true, title: 'Delete photo'
    %>
  </td>
</tr>

app/views/admin/albums/_single_index_album.html.erb
<tr class="pic-div">
  <td class="image">
    <a href="<%= edit_admin_album_path(album) %>">
      <% if !album.cover.nil? %>
        <% if album.cover.length != 0 %>
          <div class="album-cover">
            <img src="<%= album.cover %>" alt="album cover"  width="50px" />
          </div>
        <% else %>
          <i class="glyphicon glyphicon-folder-open"></i>
        <% end %>
      <% else %>
        <i class="glyphicon glyphicon-folder-open"></i>
      <% end %>
    </a>
  </td>
  <td>
    <p><%= link_to album.name, edit_admin_album_path(album) %></p>
  </td> 
  <td class="hidden-xs"><%= album.created_at.strftime('%Y-%m-%d ') %></td>
  <td class="hidden-xs"><%= album.created_by %></td>
  <td class="buttons pull-right">
    <%= link_to 'Edit',
      edit_admin_album_path(album),
      class: "btn btn-info"
    %>
    <%= link_to 'Delete',
      [:admin, album],
      method: :delete,
      class: 'btn btn-danger delete-album',
      data: { confirm: 'Are you sure you want to delete this album?' }
    %>  
  </td> 
</tr>

app/views/admin/albums/_single_pic.html.erb
<tr>
  <td class="image gallery">
    <%= link_to(image_tag(picture.upload.url(:small),
    id: picture.id, 
    alt: "photo", 
    class: "img draggable ui-widget-content" ),
    picture.upload.url,
    target: '_blank'
    ) 
    %>
  </td>
  <td>
    <%= picture.upload.original_filename %>
  </td>
  <td class="buttons pull-right">
    <%= link_to 'Private',
      admin_pictures_make_protected_path(picture),
      class: "btn #{ is_protected(picture) } protected",
      remote: true, title: 'Private'
    %>
    <%= link_to 'Delete',
      [:admin, picture],
      method: :delete,
      class: 'btn btn-danger',
      data: { confirm: 'Are you sure you want to delete this picture?', toggle: 'tooltip', placement: 'bottom' },
      remote: true, title: 'Delete photo'
    %>
  </td>
</tr>

app/views/admin/albums/create.js.erb
<% if @result %>

	$('.album-list').append("<%= j render 'single_album', album: @album%>")
	$('.album-index-list').append("<%= j render 'single_index_album', album: @album %>")
	App.hideShowAlbumForm()
	$('#album_name').val('');
	App.flash('The album was created successfully!', 'notice');

<% else %>

	App.flash('There was an error in updating the album</p><ul><% @album.errors.each do |e,m| %><li><%= e %>: <%= m %></li><% end %></ul>', 'alert');

<% end %>

app/views/admin/albums/edit.html.erb
<h3>Edit Album</h3>
<hr>
<%= render 'form' %>

app/views/admin/albums/index.html.erb
<h3>Albums</h3>
<br>


<table class="table-custom album-index-list">
  <tr>
    <thead>
      <th></th>
      <th>Name</th>
      <th class="hidden-xs">Created at</th>
      <th class="hidden-xs">Created by</th>
      <th></th>
    </thead>  
  </tr>

  <% @albums.each do |album| %>
    <tr class="pic-div">
      <td class="image">
        <a href="<%= edit_admin_album_path(album) %>">
          <% if !album.cover.nil? %>
            <% if album.cover.length != 0 %>
              <div class="album-cover">
                <img src="<%= album.cover %>" alt="album cover"  width="50px" />
              </div>
            <% else %>
              <i class="glyphicon glyphicon-folder-open"></i>
            <% end %>
          <% else %>
            <i class="glyphicon glyphicon-folder-open"></i>
          <% end %>
        </a>
      </td>
      <td>
        <p><%= link_to album.name, edit_admin_album_path(album) %></p>
      </td> 
      <td class="hidden-xs"><%= album.created_at.strftime('%Y-%m-%d ') %></td>
      <td class="hidden-xs"><%= album.created_by %></td>
      <td class="buttons pull-right">
        <%= link_to 'Edit',
          edit_admin_album_path(album),
          class: "btn btn-info"
        %>
        <%= link_to 'Delete',
          [:admin, album],
          method: :delete,
          class: 'btn btn-danger delete-album',
          data: { confirm: 'Are you sure you want to delete this album?' }
        %>  
      </td> 
    </tr>
  <% end %>      
</table>
<%= will_paginate @albums %>
  

   

app/views/admin/albums/new.html.erb
<h3>New album</h3>
<hr>
<%= render 'form' %>

app/views/admin/albums/update.js.erb
<% if [:admin, @result] %>
	<% if [:admin, @save] %>
    <% if @type == 'image' %>
      if($('.pic-list').length > 0){
		    $(".pic-list").append("<%=  j render 'single_pic', picture: @new_picture %>");
      }else{
        $('.no-content').remove();
        $('.end-of-form').after("<table class='table-custom pic-list'><%=  j render 'single_pic', picture: @new_picture %></table>");
      }
    <% else %>  
      $(".file-list").append("<%=  j render 'single_file', picture: @new_picture %>");
    <% end %>  
	<% end %>
<% else %>
	App.flash('There was an error in updating the album</p><ul><% @album.errors.each do |e,m| %><li><%= e %>: <%= m %></li><% end %></ul>', 'alert');
<% end %>