config/routes.rb
Rails.application.routes.draw do
    
  scope module: 'public' do
    
    resources :pictures
    resources :albums do
      resource :pictures
    end

    root 'albums#index'

    delete "log_out", to: "sessions#destroy", as: "destroy_user_session"
    get "log_in", to: "sessions#new", as: "new_user_session"
    post "confirm_account_create", to: "confirmations#create", as: "confirmations"
    get "confirm_account_edit", to: "confirmations#edit", as: "confirmations_edit"
    post "confirm_account_update", to: "confirmations#update", as: "confirmations_update"


    get 'password_new', to: "passwords#new", as: 'password_new'
    post 'password_create', to: "passwords#create", as: 'password_create'
    get 'password_edit', to: "passwords#edit", as: 'password_edit'
    post 'password_update', to: 'passwords#update', as: 'password_update'

    resources :users
    resources :sessions
    resources :confirmations
    resources :passwords
  end
  

  namespace :admin do
    
    resources :pictures
    resources :albums do
      resource :pictures
    end

    root 'albums#index'

    delete "log_out", to: "sessions#destroy", as: "destroy_user_session"
    get "pictures/:id/make_protected", to: "pictures#make_protected", as: "pictures_make_protected"
    get "sign_up", to: "users#new", as: "new_user_registration"
    


    resources :users
    resources :sessions
    #resources :confirmations

  end
  
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Photos</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/png" href="/assets/photos-logo-icon.png">
  <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>
<body class="admin">
  <nav class="navbar navbar-photos navbar-fixed-top" role="navigation">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/"><%= image_tag("photos-logo-transparent.png", alt: "Photos logo") %> Photos</a>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <% if current_user %>

            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Logged in as <%= current_user.name %> <b class="caret"></b></a>
              <ul class="dropdown-menu menu-arrow">
                <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
                <li class="divider"></li>
                <li><%= link_to 'Account', edit_admin_user_path(current_user) %></li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to 'Log in', new_user_session_path %></li>
          <% end %>
          <% if current_user && current_user.admin %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Admin <b class="caret"></b></a>
              <ul class="dropdown-menu menu-arrow">
                <li><%= link_to 'All albums', admin_albums_path %></li>
                <li class="divider"></li>
                <li><%= link_to 'Add new member', admin_new_user_registration_path %></li>
                <li class="divider"></li>
                <li><%= link_to 'Edit members', admin_users_path %></li>
              </ul>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    <div class="row content">
      <div class="left-sidebar">
        <%= render partial: 'admin/albums/index', locals: { albums: Album.all.order(:created_at), album: Album.new} %>
        <div class="sidebar-push-down"></div>
      </div>
      <div class="col-md-2 hidden-sm">
      </div>
      <div class="col-md-10 col-sm-12 col-xs-12 main-content">
        <div class="sidebar-wrapper hidden-lg hidden-md">
          <div class="sidebar-responsive">
            <div class="sidebar-toggle">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </div>  
          </div>
        </div>
        <div class="main">  
          <%= yield %>
        </div>
      </div>
    </div>
  </div>
  <div class="modal fade">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-body">
          <div class="modal-header">
            <p>Uploading... <span class="percent"></span></p>
          </div>
          <div class="progress progress-striped active">
            <div class="progress-bar"  role="progressbar" aria-valuenow="45" aria-valuemin="0" aria-valuemax="100" style="width: 45%">
              <span class="sr-only">45% Complete</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <% if alert || notice %>
    <% @flash = 'alert' if alert %>
    <% @flash = 'notice' if notice %>
    <%= render 'flash', flash: @flash %>
  <% end %>

  <div id="notice" class="alert alert-success">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <div class="message">
      <%= notice %>
    </div>
  </div>

  <div id="alert" class="alert alert-danger">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <div class="message">
      <% if alert.kind_of?(Hash) %>
        <ul style="list-style:none;">
          <% alert.each do |e, m| %>
            <li><%= e %>: <%= m[0] %></li>
          <% end %>
        </ul>
      <% else %>
        <%= alert %>
      <% end %>
    </div>
  </div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Photos</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-54220024-1', 'auto');
    ga('send', 'pageview');

  </script>
  <!--[if lt IE 9]>
    
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
  
</head>
<body class="public">

  <% if current_user %>
    <div class="navbar navbar-default" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/"><%= image_tag("photos-logo-transparent.png", alt: "Photos logo") %> Photos</a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <% if current_user %>

              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Logged in as <%= current_user.name %> <b class="caret"></b></a>
                <ul class="dropdown-menu menu-arrow">
                  <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>

                  <li><%= link_to 'Account', edit_user_path(current_user) %></li>
                </ul>
              </li>
            <% else %>
              <li><%= link_to 'Log in', new_user_session_path %></li>
            <% end %>
            <% if current_user && current_user.admin %>
              <%= link_to 'Admin', admin_root_path, class: 'navbar-text' %>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  <% end %>
  <div class="container container-main">
    <div class="row">
      <div class="col-md-2"></div>
      <div class="col-md-8 main">
        <%= yield %>
      </div>
      <div class="col-md-2"></div>
    </div>
  </div>
  <div class="clearfix"></div>
  <div class="footer-wrapper container">
    <% if current_user %>
      <script type="text/javascript" src="http://www.skypeassets.com/i/scom/js/skype-uri.js"></script>
      <div class="row footer">

        <div class="col-md-8 col-md-offset-2">
          <div class="row">
            <div class="col-md-2 col-sm-2">
              <ul class="social-1">
                <li><a href="https://www.facebook.com/jason.carty1"></a></li>
                <li id="twitter"><a  href="https://twitter.com/jasoncarty42"></a></li>
              </ul>
            </div>
            <div class="col-md-8 col-sm-8 footer-text">
              <p><a href="mailto:jason@jcartydesign.com">© 2014 Created and designed by Jason Carty</a></p>
            </div>
            <div class="col-md-2 col-sm-2">
              <ul class="social-2 float-right">

                <li><a id="skype" ></a></li>
                <li id="linkedin"><a href="https://www.linkedin.com/profile/view?id=44047863&trk=nav_responsive_tab_profile"></a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>


<div id="SkypeButton_Call_jason.carty1_1">
  <script type="text/javascript">
  //   Skype.ui({
  //     "name" : "chat",
  //     "element": "skype",
  //     "participants": ["jason.carty1"]

  //   });
   </script>
</div>


  <% if alert || notice %>
    <% @flash = 'alert' if alert %>
    <% @flash = 'notice' if notice %>
    <%= render 'flash', flash: @flash %>
  <% end %>

  <div id="notice" class="alert alert-success">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <%= notice %>
  </div>

  <div id="alert" class="alert alert-danger">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <% if alert.kind_of?(Hash) %>
      <ul style="list-style:none;">
        <% alert.each do |e, m| %>
          <li><%= e %>: <%= m[0] %></li>
        <% end %>
      </ul>
    <% else %>
      <%= alert %>
    <% end %>
  </div>
</body>
</html>